[project]
name = "ths_whatsapp"
authors = [
    { name = "THS Solution", email = "info@thssolution.com"}
]
description = "WhatsApp Meta Cloud API integration for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=16.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# Required for Frappe Cloud / Marketplace compatibility checks
# https://docs.frappe.io/cloud/custom-apps/app-versioning/versioning
[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"

[tool.bench.dev-dependencies]

[deploy.dependencies.apt]
packages = []
